version: "3.3"

services:
  # node service container: node:12-alpine
  # $ docker-compose run node $command ...
  node:
    build:
      context: ./ # build from ./Dockerfile
      args:
        # use current working user id
        UID: $UID
    logging:
      driver: json-file
    ports:
      # http://localhost:32300 => service://node:3000
      - "32300:3000"
    volumes:
      # ./package.json => service://node:/package.json (read + write)
      ## $ npm i --prefix '/' => module install in service://node:/node_modules/
      - ./package.json:/package.json:rw
      - ./package-lock.json:/package-lock.json:rw
      
      # ./ => service:node:/work/
      - ./:/work/
    environment:
      TZ: Asia/Tokyo
