# ver 3.6 >= required: enable '-w' option for 'docker-compose exec'
version: "3.6"

services:
  # cli service container: node:12-alpine
  # $ docker-compose exec cli $command ...
  cli:
    build:
      context: ./ # build from ./Dockerfile
      args:
        # use current working user id
        UID: $UID
    logging:
      driver: json-file
    # tcp://localhost:<port> => service://cli:<port>
    network_mode: host
    # enable terminal
    tty: true
    volumes:
      # ./ => service:node:/work/
      - ./:/work/
    environment:
      TZ: Asia/Tokyo
